<a href="https://colab.research.google.com/github/greeshmavrmac/flyrank-ml-internship/blob/main/w01_research_question_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Research Question


## 1. My Lane (or Freestyle) and Why

I chose the **Content Refresh Prioritization** lane because it focuses on identifying webpages that may need updates based on their search performance and content-related metrics. This topic interests me because improving existing content can help teams make better decisions about where to spend their time and effort.

I selected this lane because it combines data analysis with practical decision-making. Instead of reviewing every page manually, I want to use data to identify pages that are more likely to benefit from a content refresh. During this internship, I hope to understand which factors are related to declining performance and how machine learning can support this process. My lane choice is provisional, and I may refine it as I learn more from the dataset.



## 2. The Question

### Search Question

Which webpages are most likely to benefit from a content refresh based on their search performance and content-related features?

### Unit of Analysis

Individual webpages.

### Output

A ranked list of webpages that are likely to benefit from a content review.

### Action

The content or SEO team can review the highest-ranked pages first and decide whether they should be updated or improved.

### Cost of a Wrong Recommendation

If a page is incorrectly recommended for a refresh, time and effort may be spent on a page that does not need changes. If an important page is missed, its performance may continue to decline. Therefore, the recommendations should support human decision-making rather than replace it.

### Why Data or ML Can Help

The dataset contains many webpages and several performance-related features. Machine learning can identify useful patterns that may not be obvious through manual analysis and help prioritize pages more efficiently.

## 3. Quick Look at the Data

In [ ]:
import os
import sys
import subprocess
import pandas as pd

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/flyrank-bih/flyrank-ml-internship-starter"
REPO_DIR = "flyrank-ml-internship-starter"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Total Pages:", len(df))
print("Declining Rate:", round((df["trend_direction"].str.lower() == "down").mean(), 3))
print("Average CTR:", round(df["ctr"].mean(), 3))
print("Average Position:", round(df["avg_position"].mean(), 2))

Total Pages: 30000
Declining Rate: 0.542
Average CTR: 0.511
Average Position: 16.34


## 3. Quick Look at the Data

The starter dataset contains **30,000 webpages**. I observed that the declining rate is **0.542**. I also calculated the average CTR as **0.511** and the average search position as **16.34**.

These values provide a useful overview of the dataset and support my choice of the Content Refresh Prioritization lane. They show that the dataset contains enough information to explore patterns related to declining content and page performance. This project is not only about training a model but also about understanding the data and using it to support better content review decisions.

## 4. Careful Words

The observations in this notebook are based only on the available dataset and should be considered directional rather than definitive. This work does not explain or predict Google's ranking algorithm. The results are intended to support decision-making and should always be reviewed before taking action.

## 5. Self-Check

- ✅ I selected a provisional lane.
- ✅ I defined my research question.
- ✅ I identified the unit of analysis.
- ✅ I explained the expected output and the action it supports.
- ✅ I described the cost of an incorrect recommendation.
- ✅ I included real numbers from the starter dataset.
- ✅ I used careful language and avoided unsupported claims.